version: '3.8'
services:
  drupal:
    image: drupal:latest
    # We verwijderen de directe poortmapping, want Nginx gaat het verkeer regelen
    depends_on:
      - mysql
    volumes:
      - drupal-data:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mysql-data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal
volumes:
  drupal-data:
  mysql-data:
